info:
  component:webparser
spring:
  config:
    name: application
  application:
    name: webparser
server:
  port: 8081

logging:
  file: ${user.home}/webparser.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    ROOT: INFO

selenium:
  webdriver:
    chrome: ${user.home}/Downloads/chromedriver

snap:
  save:
    path: ${user.home}
    url: http://www.amazon.com/

---
spring:
  profiles: dev

selenium:
  webdriver:
    chrome: ${user.home}/chromedriver

snap:
  save:
    path: ${user.home}
    url: http://www.amazon.com/


---
spring:
  profiles: test


selenium:
  webdriver:
    chrome: /srv/vhosts/webscreen/driver/chromedriver

snap:
  save:
    path: /srv/vhosts/webscreen/snapshots
    url: http://www.amazon.com/

---
spring:
  profiles: prod

selenium:
  webdriver:
    chrome:

snap:
  save:
    path:
    url: